description: Provisione infraestrutura para pipeline de dados como produto em escala. 

name: skynet-analytics-stack

displayName: Stack Analytics

picture: "stack.png"

category: Analytics

compatibility:
  - docker

technologies: ["docker", "python", "AWS CDK"]

about: about.md

useCases:
  - title: Criar sua stack Analítica
    content: useCase.md
    stackfile: stackfiles/default.yaml
